"""chapter_management_progress_proposals

Revision ID: f9a50259f31d
Revises: ab48b6d18e9f
Create Date: 2026-10-01 04:20:09.507294+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a50259f31d'
down_revision: Union[str, None] = 'ab48b6d18e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('proposer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('proposed_data', sa.JSON(), nullable=False),
    sa.Column('current_data', sa.JSON(), nullable=False),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_proposals_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_proposals_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_proposals_proposer_id'), ['proposer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_proposals_status'), ['status'], unique=False)

    op.create_table('chapter_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('rights_basis', sa.Text(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_resources_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_resources_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_resources_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_resources_verification_status'), ['verification_status'], unique=False)

    op.create_table('chapter_watches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('notify_preference', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', 'chapter_id', name='uq_user_chapter_watch')
    )
    with op.batch_alter_table('chapter_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_watches_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_watches_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_watches_user_id'), ['user_id'], unique=False)

    op.create_table('user_chapter_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('reading_state', sa.String(length=32), nullable=False),
    sa.Column('bookmark_page', sa.Integer(), nullable=True),
    sa.Column('bookmark_note', sa.String(length=255), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_user_chapter_progress')
    )
    with op.batch_alter_table('user_chapter_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_chapter_progress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_chapter_progress_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_chapter_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('pagination_basis', sa.String(length=64), nullable=False, server_default='edition_page_numbers'))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('page_start',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('page_end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_chapters_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_chapters_parent_id_chapters', 'chapters', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('community_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_chapters', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('target_snapshot', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('revalidation_required', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('support_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revalidation_required', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_offers', schema=None) as batch_op:
        batch_op.drop_column('revalidation_required')

    with op.batch_alter_table('community_requests', schema=None) as batch_op:
        batch_op.drop_column('revalidation_required')
        batch_op.drop_column('target_snapshot')
        batch_op.drop_column('target_chapters')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chapters_parent_id_chapters', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chapters_parent_id'))
        batch_op.alter_column('page_end',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('page_start',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('version')
        batch_op.drop_column('pagination_basis')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('order_index')
        batch_op.drop_column('chapter_code')

    with op.batch_alter_table('user_chapter_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_chapter_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_chapter_progress_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_user_chapter_progress_book_id'))

    op.drop_table('user_chapter_progress')
    with op.batch_alter_table('chapter_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_watches_user_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_watches_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_watches_book_id'))

    op.drop_table('chapter_watches')
    with op.batch_alter_table('chapter_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_resources_verification_status'))
        batch_op.drop_index(batch_op.f('ix_chapter_resources_owner_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_resources_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_resources_book_id'))

    op.drop_table('chapter_resources')
    with op.batch_alter_table('chapter_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_chapter_proposals_proposer_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_proposals_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_proposals_book_id'))

    op.drop_table('chapter_proposals')
    # ### end Alembic commands ###
