"""requests_library_offers_expansion

Revision ID: ab48b6d18e9f
Revises: f583fdfb2d32
Create Date: 2026-10-01 03:33:48.563700+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab48b6d18e9f'
down_revision: Union[str, None] = 'f583fdfb2d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_scope', sa.JSON(), nullable=False),
    sa.Column('rights_basis', sa.Text(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('recipient_scope', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorized_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorized_collections_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorized_collections_status'), ['status'], unique=False)

    op.create_table('library_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('reading_status', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', 'entry_type', name='uq_user_book_entry_type')
    )
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_entries_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_entries_user_id'), ['user_id'], unique=False)

    op.create_table('user_warnings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_user_id', sa.String(length=36), nullable=False),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.String(length=64), nullable=False),
    sa.Column('appeal_status', sa.String(length=32), nullable=False),
    sa.Column('appeal_note', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_warnings_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_warnings_subject_user_id'), ['subject_user_id'], unique=False)

    op.create_table('assembly_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manifest_data', sa.JSON(), nullable=False),
    sa.Column('coverage_summary', sa.JSON(), nullable=False),
    sa.Column('output_file_path', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['authorized_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assembly_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assembly_jobs_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assembly_jobs_status'), ['status'], unique=False)

    op.create_table('collection_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('start_page <= end_page AND start_page >= 1', name='chk_contrib_page_order'),
    sa.ForeignKeyConstraint(['collection_id'], ['authorized_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_contributions_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_contributions_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_contributions_verification_status'), ['verification_status'], unique=False)

    op.create_table('copy_coverage_ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('copy_id', sa.String(length=36), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('pagination_basis', sa.String(length=64), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=False),
    sa.Column('source_description', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('start_page <= end_page AND start_page >= 1', name='chk_coverage_page_order'),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copy_coverage_ranges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copy_coverage_ranges_copy_id'), ['copy_id'], unique=False)

    op.create_table('request_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('need_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('copy_id', sa.String(length=36), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('notification_status', sa.String(length=32), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=128), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['need_id'], ['community_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('need_id', 'owner_user_id', 'copy_id', name='uq_request_match_copy')
    )
    with op.batch_alter_table('request_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_matches_copy_id'), ['copy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_matches_need_id'), ['need_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_matches_notification_status'), ['notification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_matches_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_matches_resource_id'), ['resource_id'], unique=False)

    op.create_table('support_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('need_id', sa.String(length=36), nullable=False),
    sa.Column('provider_user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_organization_id', sa.String(length=36), nullable=True),
    sa.Column('offer_type', sa.String(length=32), nullable=False),
    sa.Column('copy_id', sa.String(length=36), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('covered_ranges', sa.JSON(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_duration_days', sa.Integer(), nullable=False),
    sa.Column('coarse_pickup_area', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rights_snapshot', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['need_id'], ['community_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_offers_copy_id'), ['copy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_offers_need_id'), ['need_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_offers_provider_organization_id'), ['provider_organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_offers_provider_user_id'), ['provider_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_offers_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_offers_status'), ['status'], unique=False)

    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=32), nullable=False, server_default='published'))
        batch_op.add_column(sa.Column('format', sa.String(length=32), nullable=False, server_default='physical'))
        batch_op.add_column(sa.Column('is_partial', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('coverage_summary', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_book_copies_visibility'), ['visibility'], unique=False)

    with op.batch_alter_table('borrow_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('offer_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_borrow_requests_need_id'), ['need_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrow_requests_offer_id'), ['offer_id'], unique=False)
        batch_op.create_foreign_key('fk_borrow_requests_need_id', 'community_requests', ['need_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_borrow_requests_offer_id', 'support_offers', ['offer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('community_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('edition_label', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('scope_type', sa.String(length=32), nullable=False, server_default='full_book'))
        batch_op.add_column(sa.Column('page_range', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('pagination_basis', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('quantity_fulfilled', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('duration_days_needed', sa.Integer(), nullable=False, server_default='14'))
        batch_op.add_column(sa.Column('urgency', sa.String(length=32), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('urgency_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('accepted_conditions', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('edition_match_strict', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=32), nullable=False, server_default='public'))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_community_requests_isbn'), ['isbn'], unique=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_upcoming_need', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('snooze_until')
        batch_op.drop_column('notify_upcoming_need')

    with op.batch_alter_table('community_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_requests_isbn'))
        batch_op.drop_column('version')
        batch_op.drop_column('visibility')
        batch_op.drop_column('description')
        batch_op.drop_column('edition_match_strict')
        batch_op.drop_column('accepted_conditions')
        batch_op.drop_column('urgency_reason')
        batch_op.drop_column('urgency')
        batch_op.drop_column('duration_days_needed')
        batch_op.drop_column('quantity_fulfilled')
        batch_op.drop_column('pagination_basis')
        batch_op.drop_column('page_range')
        batch_op.drop_column('scope_type')
        batch_op.drop_column('edition_label')
        batch_op.drop_column('isbn')

    with op.batch_alter_table('borrow_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_borrow_requests_need_id', type_='foreignkey')
        batch_op.drop_constraint('fk_borrow_requests_offer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_borrow_requests_offer_id'))
        batch_op.drop_index(batch_op.f('ix_borrow_requests_need_id'))
        batch_op.drop_column('offer_id')
        batch_op.drop_column('need_id')

    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_copies_visibility'))
        batch_op.drop_column('coverage_summary')
        batch_op.drop_column('available_from')
        batch_op.drop_column('is_partial')
        batch_op.drop_column('format')
        batch_op.drop_column('visibility')

    with op.batch_alter_table('support_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_offers_status'))
        batch_op.drop_index(batch_op.f('ix_support_offers_resource_id'))
        batch_op.drop_index(batch_op.f('ix_support_offers_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_offers_provider_organization_id'))
        batch_op.drop_index(batch_op.f('ix_support_offers_need_id'))
        batch_op.drop_index(batch_op.f('ix_support_offers_copy_id'))

    op.drop_table('support_offers')
    with op.batch_alter_table('request_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_matches_resource_id'))
        batch_op.drop_index(batch_op.f('ix_request_matches_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_matches_notification_status'))
        batch_op.drop_index(batch_op.f('ix_request_matches_need_id'))
        batch_op.drop_index(batch_op.f('ix_request_matches_copy_id'))

    op.drop_table('request_matches')
    with op.batch_alter_table('copy_coverage_ranges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copy_coverage_ranges_copy_id'))

    op.drop_table('copy_coverage_ranges')
    with op.batch_alter_table('collection_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_contributions_verification_status'))
        batch_op.drop_index(batch_op.f('ix_collection_contributions_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_collection_contributions_collection_id'))

    op.drop_table('collection_contributions')
    with op.batch_alter_table('assembly_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assembly_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_assembly_jobs_collection_id'))

    op.drop_table('assembly_jobs')
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_warnings_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_warnings_related_entity_id'))

    op.drop_table('user_warnings')
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_library_entries_book_id'))

    op.drop_table('library_entries')
    with op.batch_alter_table('authorized_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorized_collections_status'))
        batch_op.drop_index(batch_op.f('ix_authorized_collections_book_id'))

    op.drop_table('authorized_collections')
    # ### end Alembic commands ###
